export const JWT = 'jwt'
export const USER = 'user'
export const CANCEL_EDIT_MESSAGE = 'Are you sure you want to cancel editing this track? Any changes will not be saved!'
export const DELETE_MESSAGE = 'Are you sure you want to delete this track?'
export const NO_CATEGORY_MESSAGE = 'You must select one or more categories!'
